// This file was autogenerated by Hardhat, do not edit it.
// prettier-ignore
// tslint:disable
// eslint-disable
// biome-ignore format: see above

export interface PaymentProcessor$Type {
  readonly _format: "hh3-artifact-1";
  readonly contractName: "PaymentProcessor";
  readonly sourceName: "contracts/PaymentProcessor.sol";
  readonly abi: [{"anonymous":false,"inputs":[{"indexed":true,"internalType":"uint256","name":"paymentId","type":"uint256"},{"indexed":true,"internalType":"address","name":"payer","type":"address"},{"indexed":false,"internalType":"uint256","name":"amount","type":"uint256"},{"indexed":false,"internalType":"uint256","name":"timestamp","type":"uint256"}],"name":"PaymentReceived","type":"event"},{"inputs":[],"name":"pay","outputs":[],"stateMutability":"payable","type":"function"},{"inputs":[],"name":"paymentCounter","outputs":[{"internalType":"uint256","name":"","type":"uint256"}],"stateMutability":"view","type":"function"}];
  readonly bytecode: "0x6080604052348015600e575f5ffd5b5061014d8061001c5f395ff3fe608060405260043610610028575f3560e01c80631b9265b81461002c57806376840b6014610036575b5f5ffd5b61003461005c565b005b348015610041575f5ffd5b5061004a5f5481565b60405190815260200160405180910390f35b5f34116100a15760405162461bcd60e51b815260206004820152600f60248201526e105b5bdd5b9d081c995c5d5a5c9959608a1b604482015260640160405180910390fd5b5f805490806100af836100f3565b90915550505f54604080513481524260208201523392917f1ccb44f7994f1a3d2e759376c53231768e4c9cd9b230ad05d26d158cf6ac66cf910160405180910390a3565b5f6001820161011057634e487b7160e01b5f52601160045260245ffd5b506001019056fea26469706673582212209ca04a6ce1d0284e9312fbcd520e32bad95046643a6c04bcba4e3e176fe0227764736f6c634300081c0033";
  readonly deployedBytecode: "0x608060405260043610610028575f3560e01c80631b9265b81461002c57806376840b6014610036575b5f5ffd5b61003461005c565b005b348015610041575f5ffd5b5061004a5f5481565b60405190815260200160405180910390f35b5f34116100a15760405162461bcd60e51b815260206004820152600f60248201526e105b5bdd5b9d081c995c5d5a5c9959608a1b604482015260640160405180910390fd5b5f805490806100af836100f3565b90915550505f54604080513481524260208201523392917f1ccb44f7994f1a3d2e759376c53231768e4c9cd9b230ad05d26d158cf6ac66cf910160405180910390a3565b5f6001820161011057634e487b7160e01b5f52601160045260245ffd5b506001019056fea26469706673582212209ca04a6ce1d0284e9312fbcd520e32bad95046643a6c04bcba4e3e176fe0227764736f6c634300081c0033";
  readonly linkReferences: {};
  readonly deployedLinkReferences: {};
  readonly immutableReferences: {};
  readonly inputSourceName: "project/contracts/PaymentProcessor.sol";
  readonly buildInfoId: "solc-0_8_28-3603651f40932876be7e3e7d636b7c786262e9a1";
};

import "hardhat/types/artifacts";
declare module "hardhat/types/artifacts" {
  interface ArtifactMap {
    ["PaymentProcessor"]: PaymentProcessor$Type;
    ["contracts/PaymentProcessor.sol:PaymentProcessor"]: PaymentProcessor$Type;
  }
}